# Generated by Django 4.1.1 on 2022-10-12 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_variation_dish_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes_model',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dishes_model',
            name='stock',
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size'), ('type', 'type')], max_length=50),
        ),
        migrations.CreateModel(
            name='Price_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dishes_model')),
                ('varitaion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.variation')),
            ],
        ),
    ]
