# Generated by Django 4.1.1 on 2022-10-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_dishes_model_price_remove_dishes_model_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes_model',
            name='ingredients',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('size', 'size')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Price_Stock',
        ),
    ]
