# Generated by Django 4.1.1 on 2022-10-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dishes_model_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes_model',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dishes_model',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
