# Generated by Django 4.1.1 on 2022-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_dishes_model_description_and_more'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='variation',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='variation',
            field=models.ManyToManyField(blank=True, null=True, to='app.variation'),
        ),
    ]
